name = "Tess Mod Pack"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaa6f358af4e2e949e958b4c53f421b762d80a11b5825152911418515dcde550"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
