name = "Moddy McModpackface"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1c0552ab537b73d978595ea3b3d741934ca91e765312f91be278836b0db12f5"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "global_packs/required_data"
