name = "Tess Mod Pack"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "001b97e8125a01d084325817f0dbb842da2757fef9fc95e9d96e592133bc8b61"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
