name = "Moddy McModpackface"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbc79af3fa2fa5b0efd5fee730508b564a2749537db93898e509918c9be2a80b"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "global_packs/required_data"
