name = "Moddy McModpackface"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bf6560556e05e509acb3105933f4ca560f9d3f8c2ac75c948b0a1a1a1efdb15"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "global_packs/required_data"
