name = "Moddy McModpackface"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "v1/index.toml"
hash-format = "sha256"
hash = "d16eb4c5ac9501b89cb5334d7ccebd1023ce13e13e86427ab255cc51f63d6698"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"

[options]
datapack-folder = "global_packs/required_data"
meta-folder-base = "v1"
