name = "Tess Mod Pack"
author = "pluumenbrownie"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "168bc7912952cf1d4097834144483265ac6187df35f0a3cd6bdcb21f220e345b"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4-beta.1"
